name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    uses: s3ntin3l8/.github/.github/workflows/release-please.yml@e99be0ab019a9e7fb07cfdbee5f03c81a66542cc # main @ 2026-09-05

  build-docker:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: s3ntin3l8/.github/.github/workflows/docker-publish.yml@ec085dff95c3482b513590b14b27c8b9713df428 # main @ 2026-09-11
    with:
      image-name: "s3ntin3l8/${{ github.event.repository.name }}"
      push-release: true
      release-tag: ${{ needs.release-please.outputs.tag_name }}
    secrets: inherit

  build-docker-web:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: s3ntin3l8/.github/.github/workflows/docker-publish.yml@ec085dff95c3482b513590b14b27c8b9713df428 # main @ 2026-09-11
    with:
      image-name: "s3ntin3l8/${{ github.event.repository.name }}-web"
      push-release: true
      release-tag: ${{ needs.release-please.outputs.tag_name }}
      dockerfile: "apps/web/Dockerfile"
      build-args: |
        NEXT_PUBLIC_LOGODEV_TOKEN=${{ vars.NEXT_PUBLIC_LOGODEV_TOKEN }}
    secrets: inherit
